name: hw2_env
channels:
  - pytorch
  - defaults
dependencies:
  - python 3.8
  - pytorch = 1.9.0
  - torchvision
  - pip
  - pip:
    - opencv-python
    - matplotlib
    - tqdm
    - pycocotools
    - PyYAML
    - python-box
    - clearml